### ISSUE TITLE
Set up ES Lint

### ISSUE THREAD

**Issue by bailee-crandley** [juroc95/walktober#61]
Set up ES Lint
https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

Acceptance criteria:
- [x] ES Lint runs when we type `npm lint`
- [x] Searches every file and cleans it up

**Comment by bailee-crandley** [comment]
I've heard that it is dangerous to use var in any JS based language (JS, TS, React), so it would be great if ES Lint could flag us anytime var is used in those files.

**Comment by NathanMoes** [comment]
Currently checking to see if I can make it do the changes automaticly as implied in the "and cleans it up". Currently it will just run every time you compile with ionic serve, and with vs code plugin it also gives feedback before then. Already has the stuff in it tellling you to not use var, and to use let or const instead.

**Comment by NathanMoes** [comment]
Somehow broke it again
Will need to redo

**Comment by NathanMoes** [comment]
script is npm run lint. Need to include run, as npm run "insert" runs the script called "insert". Etc. Also. EVERYONE should use vs code and use the eslint extension/plugin. I do not reccomend using the command line for the error checking. Like, it works and whatnot but will give some weird errors related to differences in unix/linux file paths and windows for local files if on windows. BUT the npm run lint will also run prettier and should clean things up automaticly when invoked. Though NOT ALL THINGS CAN BE RESOLVED AUTOMAICLY. Thus, EVERYONE should use vs code with eslint extention.
